# Generated by Django 4.1.3 on 2022-11-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
