# Generated by Django 4.1.3 on 2022-12-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_book_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='upload',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
